// Code generated by go-genconstructor; DO NOT EDIT.

package templer

func NewRootParam(
	types []Type,
) RootParam {
	return RootParam{
		types: types,
	}
}

func NewPackage(
	name string,
	path string,
) Package {
	return Package{
		name: name,
		path: path,
	}
}

func NewParam(
	name string,
	typ Type,
) Param {
	return Param{
		name: name,
		typ:  typ,
	}
}

func NewArg(
	name string,
	typ Type,
) Arg {
	return Arg{
		Param: Param{
			name: name,
			typ:  typ,
		},
	}
}

func NewMethod(
	args []Arg,
	responses []Param,
) Method {
	return Method{
		args:      args,
		responses: responses,
	}
}

func NewPrimitiveType(
	typeName string,
) PrimitiveType {
	return PrimitiveType{
		typeKind: TypeKindPrimitive,
		typeName: typeName,
	}
}

func NewStructType(
	typeName string,
	pkg Package,
	fields []Field,
	methods []Method,
) StructType {
	return StructType{
		typeKind: TypeKindStruct,
		typeName: typeName,
		pkg:      pkg,
		fields:   fields,
		methods:  methods,
	}
}

func NewSliceType(
	itemType Type,
) SliceType {
	return SliceType{
		typeKind: TypeKindSlice,
		itemType: itemType,
	}
}

func NewMapType(
	keyType Type,
	valueType Type,
) MapType {
	return MapType{
		typeKind:  TypeKindMap,
		keyType:   keyType,
		valueType: valueType,
	}
}

func NewChannelType(
	itemType Type,
) ChannelType {
	return ChannelType{
		typeKind: TypeKindChannel,
		itemType: itemType,
	}
}
